-- Generated by docs/generate_tours_seed.mjs
-- 16 tours migrated from hellomysticegypt.com (WordPress Travel Engine)

START TRANSACTION;

-- ===== Fayoum (1 Day, €110) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '13d6e03e-b873-411f-b5d7-74244ea5b021',
  'Fayoum Oasis',
  'fayoum',
  'Discover the lush Fayoum Oasis, Egypt''s oldest oasis and a haven of green orchards, serene lakes and desert camps. Cross the remarkable Qarun Lake, tour the historic Water Wheels and visit Wadi El Rayan waterfalls on this relaxing escape from Cairo.',
  'Private air-conditioned vehicle with driver
English-speaking Egyptologist guide (placeholder)
Hotel pickup and drop-off in Cairo
Bottled water during the tour (placeholder)
Entry fees to all mentioned sites',
  'Lunch and personal expenses
Tips and gratuities
Quad bike / sand-boarding activities (optional)',
  '1 Day',
  110,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '3a46b101-add4-4990-815d-dd4c87dbe8aa',
  '13d6e03e-b873-411f-b5d7-74244ea5b021',
  1,
  'Fayoum Oasis & Qarun Lake',
  'Depart Cairo in the morning, travel to the Fayoum oasis, explore Qarun Lake (placeholder), Wadi El Rayan waterfalls and the traditional water wheels before returning to Cairo (placeholder).'
);

-- ===== Cairo (1 Day, €250) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '36d6d59a-04bf-4dae-9c37-94956dddcb4b',
  'Cairo City Tour',
  'cairo',
  'Explore the heart of Cairo: the world-famous Pyramids of Giza and the Sphinx, the treasures of the Egyptian Museum, and the vibrant lanes of Khan El Khalili bazaar, all guided by a certified Egyptologist.',
  'Private air-conditioned vehicle with driver
Certified Egyptologist guide
Hotel pickup and drop-off
Bottled water
Entry fees to the Pyramids plateau & Egyptian Museum',
  'Lunch and personal expenses
Tips and gratuities
Entry inside the Great Pyramid (optional)',
  '1 Day',
  250,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '445bea80-995e-4cf7-832b-83bddab61b19',
  '36d6d59a-04bf-4dae-9c37-94956dddcb4b',
  1,
  'Pyramids, Museum & Old Cairo',
  'Visit the Pyramids of Giza and the Sphinx, transfer to the Egyptian Museum of Antiquities, then walk through the historic Khan El Khalili bazaar (placeholder).'
);

-- ===== Luxor (1 Day, €250) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '8dbb804c-f523-4786-bc47-9c228cc9ca10',
  'Luxor Tour',
  'luxor',
  'Step into the world''s greatest open-air museum: Karnak and Luxor temples on the East Bank, and the Valley of the Kings, Hatshepsut Temple and the Colossi of Memnon on the West Bank of Luxor.',
  'Private air-conditioned vehicle with driver
Certified Egyptologist guide
Hotel pickup and drop-off in Luxor
Bottled water
Entry fees to Karnak, Valley of the Kings & Hatshepsut Temple',
  'Lunch and personal expenses
Tips and gratuities
Extra entry: Tutankhamun tomb, Deir el-Medina (optional)',
  '1 Day',
  250,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '97c0425e-7093-4760-bcc2-3a45f6053a88',
  '8dbb804c-f523-4786-bc47-9c228cc9ca10',
  1,
  'East & West Bank of Luxor',
  'Start with Karnak Temple, cross the Nile to the Valley of the Kings, visit Hatshepsut''s Temple and stop at the Colossi of Memnon (placeholder).'
);

-- ===== Aswan (2 Days, €300) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '6aa53663-8b90-4f50-a7ba-e6ff21894845',
  'Aswan Tour',
  'aswan',
  'Sail the tranquil waters of the Nile in Aswan: the High Dam, the Unfinished Obelisk, Philae Temple by boat, the Botanical Garden and the colourful Nubian village, all in two unforgettable days.',
  'Private air-conditioned vehicle with driver
Certified Egyptologist guide
Hotel pickup and drop-off in Aswan
Felucca ride on the Nile (placeholder)
Entry fees to Philae Temple & the High Dam',
  'Lunch and personal expenses
Tips and gratuities
Nubian museum tickets (optional)',
  '2 Days',
  300,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '54fd1fd2-5415-4495-9480-5afe70ab43f1',
  '6aa53663-8b90-4f50-a7ba-e6ff21894845',
  1,
  'High Dam, Obelisk & Philae Temple',
  'Tour the Aswan High Dam and the Unfinished Obelisk, then take a boat to the majestic Philae Temple of Isis and explore the Nubian village (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '59d0cc20-8606-47db-be8d-41a89a645ea1',
  '6aa53663-8b90-4f50-a7ba-e6ff21894845',
  2,
  'Nile & Nubia',
  'Enjoy a relaxing felucca sail around Elephantine Island and the Botanical Garden, with free time to explore Aswan before returning in the evening (placeholder).'
);

-- ===== Alexandria (1 Day, €120) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  'bd38a435-0ed9-47e9-b274-ea24ae42335e',
  'Alexandria Tour',
  'alexandria',
  'Visit Egypt''s Mediterranean bride: the Bibliotheca Alexandrina, the Catacombs of Kom El Shoqafa, Pompey''s Pillar and the coastal sweep of the Corniche, with glimpses of the royal heritage of Alexandria.',
  'Private air-conditioned vehicle with driver
English-speaking guide
Hotel pickup and drop-off in Alexandria
Bottled water
Entry fees to the Catacombs & Bibliotheca (placeholder)',
  'Lunch and personal expenses
Tips and gratuities
Qaitbay Castle entry (optional)',
  '1 Day',
  120,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'd5876a00-5b04-4224-9894-59099945e084',
  'bd38a435-0ed9-47e9-b274-ea24ae42335e',
  1,
  'Alexandria City Highlights',
  'Explore the Bibliotheca Alexandrina (placeholder), the Catacombs of Kom El Shoqafa and Pompey''s Pillar, then enjoy the Corniche and coastal promenade (placeholder).'
);

-- ===== Nile Trip (Cairo) (1 Day, €50) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '24cbd0f7-ffa2-47c8-a80a-91157e7ba7e4',
  'Nile Trip (Cairo)',
  'nile-trip-cairo',
  'An authentic Cairo Nile experience: board a traditional Nile boat and soak up the city lights and landmarks from the water, with a delicious onboard dinner and folklore entertainment.',
  'Nile boat cruise with dinner
Belly-dancing & Tanoura folklore show (placeholder)
Hotel pickup and drop-off in Cairo
Soft drinks and tea onboard',
  'Extra beverages
Tips and gratuities
Private cabin (for overnight cruises only)',
  '1 Day',
  50,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '92b4ce44-7fca-4186-a197-88279b638f19',
  '24cbd0f7-ffa2-47c8-a80a-91157e7ba7e4',
  1,
  'Sunset Nile Dinner Cruise',
  'Board the Nile cruise at dusk, enjoy the Cairo skyline and landmarks from the water, followed by a buffet dinner and live folklore entertainment (placeholder).'
);

-- ===== Hurghada (1 Day, €45) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '6702e2ca-493f-48db-acc1-4ffa678403d3',
  'Hurghada Day Trip',
  'hurghada',
  'A fun-filled day on the Red Sea: an optional desert safari and quad-bike ride, a snorkeling or glass-bottom boat excursion, and free time on the golden beaches of Hurghada.',
  'Private or shared transfers
Snorkeling / glass-bottom boat trip (placeholder)
Lunch on the boat (placeholder)
Beach free time
Bottled water',
  'Photo & video packages
Tips and gratuities
Personal expenses',
  '1 Day',
  45,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'f48613df-c819-4197-8c97-922fbb186bc5',
  '6702e2ca-493f-48db-acc1-4ffa678403d3',
  1,
  'Red Sea & Beach Day',
  'Red Sea snorkeling or boat trip in the morning, followed by beach time and optional desert safari in the afternoon (placeholder).'
);

-- ===== Marsa Alam (1 Day, €50) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '50875b30-51a3-4579-bcad-ae42ef29ef30',
  'Marsa Alam Tour',
  'marsa-alam',
  'Discover the unspoiled Red Sea of Marsa Alam: world-class snorkeling and diving sites, pristine beaches, and the famous dolphins of the deep blue waters.',
  'Private transfers
Snorkeling / diving trip with equipment (placeholder)
Lunch on the boat
Bottled water',
  'Extra equipment rental
Tips and gratuities
Personal expenses',
  '1 Day',
  50,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'b247a777-010d-4761-93b1-103158852697',
  '50875b30-51a3-4579-bcad-ae42ef29ef30',
  1,
  'Snorkeling, Diving & Beaches',
  'Snorkel or dive the coral reefs of Marsa Alam (placeholder), enjoy the pristine beaches and a boat lunch before returning to the resort.'
);

-- ===== Siwa Oasis (2 Days, €500) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  'bdf25ac4-e2c2-49d1-bdca-d2b9b19a5229',
  'Siwa Oasis Tour',
  'siwa-oasis',
  'Venture deep into the Western Desert to the legendary Siwa Oasis: the Oracle Temple of Amun, the Mountain of the Dead, salt lakes and hot springs, and camp beneath the vast desert stars.',
  'Private 4x4 transfers from Cairo
English-speaking Bedouin guide
Two nights accommodation (placeholder)
Orange & olive farm visit (Siwa signature)
Camping equipment for one desert night
All meals during the tour',
  'Flights
Personal expenses
Tips and gratuities',
  '2 Days',
  500,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '63394a84-c22a-4a99-8ea4-7097c178590d',
  'bdf25ac4-e2c2-49d1-bdca-d2b9b19a5229',
  1,
  'Drive to Siwa & Town Highlights',
  'Long 4x4 drive across the desert to Siwa, then visit the Temple of Amun Oracle, the Mountain of the Dead and the salt lakes at sunset (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '19245be3-c409-4e72-97c5-ae33563993dd',
  'bdf25ac4-e2c2-49d1-bdca-d2b9b19a5229',
  2,
  'Desert Camping & Springs',
  'Explore the date and olive groves, swim in Cleopatra''s hot springs, then overnight camping (optional) in the Great Sand Sea dunes before returning (placeholder).'
);

-- ===== Abydos & Dendera Temples Tour (1 Day, €105) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '9a2274b7-ad32-4270-852d-f3666e82f9a5',
  'Abydos & Dendera Temples Tour',
  'abydos-dendera-temples',
  'A deep, off-the-beaten-path day tour to two of Egypt''s most magnificent temples: the Temple of Seti I at Abydos and the beautifully preserved Hathor Temple at Dendera.',
  'Private air-conditioned vehicle with driver
Certified Egyptologist guide (placeholder)
Hotel pickup and drop-off in Luxor
Bottled water
Entry fees to Abydos & Dendera temples',
  'Lunch and personal expenses
Tips and gratuities',
  '1 Day',
  105,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '5cdaa74d-a6a0-417b-9bf8-e971d0618b43',
  '9a2274b7-ad32-4270-852d-f3666e82f9a5',
  1,
  'Abydos & Dendera',
  'Drive to Abydos to visit the temple of Seti I, then continue to Dendera to admire the magnificent Hathor temple before returning to Luxor (placeholder).'
);

-- ===== Sharm El Sheikh (1 Day, €75) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '44ce4374-733b-4751-bbf7-1cfb0fd8e03b',
  'Sharm El Sheikh Tour',
  'sharm-el-sheikh',
  'Enjoy the Red Sea Riviera of Sharm El Sheikh: snorkeling at Ras Mohammed, glass-bottom boats, the charm of Naama Bay and optional desert stargazing under Sinai''s clear skies.',
  'Private or shared transfers
Snorkeling trip to Ras Mohammed (placeholder)
Lunch on the boat
Bottled water',
  'Diving course fees
Tips and gratuities
Personal expenses',
  '1 Day',
  75,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'd38ff274-17fe-4a53-9b4a-a8c3254d1620',
  '44ce4374-733b-4751-bbf7-1cfb0fd8e03b',
  1,
  'Ras Mohammed, Naama Bay & Desert',
  'Snorkel at Ras Mohammed National Park (placeholder), relax at Naama Bay, and optionally enjoy a desert safari and Bedouin dinner in the evening.'
);

-- ===== Hurghada – Cairo Trip Program (Includes flight booking and hotel accommodation) (8 Days, €1850) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  'Hurghada – Cairo Trip Program',
  'hurghada-cairo-trip-program',
  'An 8-day package combining the Red Sea charm of Hurghada with the pyramids and museums of Cairo. Includes flights, hotel accommodation, transfers and daily excursions (placeholder itinerary).',
  'Return flights Hurghada ↔ Cairo (placeholder)
Hotel accommodation with breakfast
Daily excursions as per itinerary
Private transfers & guides
Bottled water during tours
24/7 local support',
  'International flights
Travel insurance
Optional activities & personal expenses
Tips and gratuities',
  '8 Days',
  1850,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'd83fd365-da7e-4055-b9c8-78fcdd1b07c7',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  1,
  'Arrival in Hurghada',
  'Airport pickup and transfer to your hotel, welcome briefing and free evening (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'ca9046c8-9b55-4c03-b0b7-c97f5b187576',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  2,
  'Hurghada Excursion',
  'Desert safari and quad biking, or a Red Sea snorkeling trip (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '93e01e50-7569-4a71-b925-3ce0fb91923f',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  3,
  'Fly to Cairo',
  'Transfer to the airport, flight to Cairo, evening free at the hotel (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'fe950e80-156e-41c3-9c3d-7e85b0ab488b',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  4,
  'Pyramids & Egyptian Museum',
  'Full-day guided tour of the Giza Pyramids, Sphinx and the Egyptian Museum (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'fd64087b-f26c-4150-b401-fce58e6d31a4',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  5,
  'Old Cairo & Khan El Khalili',
  'Visit Coptic Cairo, the Citadel and the vibrant Khan El Khalili bazaar (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '637a87d7-2775-44d3-955a-34cf6ae5391c',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  6,
  'Fly Back to Hurghada',
  'Flight back to Hurghada, free beach day (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'ff2d93ef-40d5-4a48-acdb-641c513a526e',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  7,
  'Free Beach Day in Hurghada',
  'Relax on the Red Sea or join an optional excursion (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '5b49ecd3-7c57-4d58-82af-f522dfbecb6a',
  '132e5328-5d42-494d-a0f1-8601e1c37cf9',
  8,
  'Departure',
  'Check-out and airport transfer for your departure (placeholder).'
);

-- ===== Hurghada Excursions Program (Includes flight booking and hotel accommodation) (8 Days, €1650) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '196ff26e-25f8-4569-9c53-113afe53392f',
  'Hurghada Excursions Program',
  'hurghada-excursions-program',
  'An 8-day Red Sea holiday based in Hurghada with a daily programme of excursions: desert safaris, island snorkeling trips, boat days and Bedouin nights (placeholder itinerary).',
  'Hotel accommodation with breakfast
Daily excursions as per itinerary
Private transfers & guides
Bottled water during tours
24/7 local support',
  'Flights
Travel insurance
Optional activities & personal expenses
Tips and gratuities',
  '8 Days',
  1650,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'eea170ee-5150-4f1c-9a01-de277bf85f5c',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  1,
  'Arrival in Hurghada',
  'Airport pickup and transfer to your hotel, welcome briefing and free evening (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '08908a85-6502-4a4b-9406-c4eddc603e8e',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  2,
  'Desert Safari & Quad Biking',
  'Afternoon desert safari, quad biking and Bedouin dinner under the stars (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'eaa3e94d-a0d3-470a-99ce-fa3acd93c1f1',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  3,
  'Red Sea Snorkeling',
  'Full-day boat trip with lunch and two snorkeling stops on the Red Sea reefs (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'a8273d0b-3ba2-4c8b-bb01-1ac3d63fcad1',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  4,
  'Giftun Island Trip',
  'Boat trip to Giftun Island, snorkeling and beach time on white sands (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '480b8b3a-05f8-4e90-88aa-a75af35a5263',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  5,
  'Free Day / Optional Trip',
  'Relax at the resort or join an optional city or shopping tour (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '336aeba8-1535-4099-9ef7-0f88d04c7301',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  6,
  'Submarine or Glass Boat',
  'Discover the Red Sea underwater world from a submarine or glass-bottom boat (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '3fdb76a8-becb-42b2-88ab-f54cc2eea096',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  7,
  'Free Beach Day',
  'Unwind on the beach with resort facilities and water sports (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '2cfb1545-f5d0-4101-9c3b-bd1aa5e1940b',
  '196ff26e-25f8-4569-9c53-113afe53392f',
  8,
  'Departure',
  'Check-out and airport transfer for your departure (placeholder).'
);

-- ===== Hurghada & Luxor Excursions Program (Includes flight booking and hotel accommodation) (8 Days, €1750) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  'Hurghada & Luxor Excursions Program',
  'hurghada-luxor-excursions-program',
  'An 8-day journey combining Red Sea relaxation in Hurghada with the ancient wonders of Luxor, including the Valley of the Kings and Karnak Temple (placeholder itinerary).',
  'Hotel accommodation with breakfast
Daily excursions as per itinerary
Private transfers & guides
Bottled water during tours
24/7 local support',
  'Flights
Travel insurance
Optional activities & personal expenses
Tips and gratuities',
  '8 Days',
  1750,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '3f5d7218-c5ee-4b10-962f-64a095a5cc36',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  1,
  'Arrival in Hurghada',
  'Airport pickup and transfer to your hotel, welcome briefing and free evening (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'ccf46935-2352-490c-a49a-3e6688a85c16',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  2,
  'Red Sea Snorkeling',
  'Full-day boat trip with lunch and snorkeling stops on the Red Sea reefs (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '7b929049-f400-430a-8968-36ec0f414664',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  3,
  'Transfer to Luxor',
  'Drive to Luxor, hotel check-in and an evening stroll on the Corniche (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'b8ff3639-c507-4327-bcc5-c48085814008',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  4,
  'Luxor East & West Bank',
  'Full-day tour of Karnak, Luxor Temple, the Valley of the Kings and Hatshepsut Temple (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '6d12cd93-9dc8-47c1-85b9-a57852180796',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  5,
  'Return to Hurghada',
  'Morning transfer back to Hurghada, free beach afternoon (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'aeb1480d-dcc7-4d66-8b39-ac5e1e574b3e',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  6,
  'Desert Safari & Bedouin Night',
  'Desert safari, quad biking and a traditional Bedouin dinner (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'a73bf3ad-5cea-413c-b71e-1d936bd8e34d',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  7,
  'Giftun Island Trip',
  'Boat trip to Giftun Island with snorkeling and beach time (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'a2534f0d-96b3-4f95-98fe-a3518766369c',
  '9607e59c-87f1-4bb9-916b-fa22352f9bc5',
  8,
  'Departure',
  'Check-out and airport transfer for your departure (placeholder).'
);

-- ===== Hurghada, Luxor & Cairo Excursions Program (Includes flight booking and hotel accommodation) (8 Days, €1999) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  'Hurghada, Luxor & Cairo Excursions Program',
  'hurghada-luxor-cairo-excursions-program',
  'The ultimate 8-day Egyptian highlight: the heights of the Giza Pyramids and Cairo, the temples of Luxor, and the Red Sea bliss of Hurghada — all in one comprehensive program (placeholder itinerary).',
  'Hotel accommodation with breakfast
Daily excursions as per itinerary
Private transfers & guides
Bottled water during tours
24/7 local support',
  'Flights
Travel insurance
Optional activities & personal expenses
Tips and gratuities',
  '8 Days',
  1999,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '9d88e8a9-510a-40f3-80b3-12fe0b5c3373',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  1,
  'Arrival in Hurghada',
  'Airport pickup and transfer to your hotel, welcome briefing and free evening (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '6b4274a1-e960-4e4c-af62-1344bd25bf1e',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  2,
  'Red Sea Snorkeling',
  'Full-day boat trip with lunch and snorkeling stops on the Red Sea reefs (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '28b3c155-365b-4972-b3f5-0e3dd665f1d3',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  3,
  'Transfer to Cairo',
  'Fly or drive to Cairo, evening free at the hotel (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  'fc7d6ee6-b421-4e64-9644-a1c91c360cd7',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  4,
  'Pyramids & Egyptian Museum',
  'Full-day guided tour of the Giza Pyramids, Sphinx and the Egyptian Museum (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '3b95082f-3bfe-4dcf-9989-efdfb03e16d5',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  5,
  'Transfer to Luxor',
  'Fly or drive to Luxor, hotel check-in and evening free (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '0d2a4f34-d212-41e3-806b-76af12aeb37d',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  6,
  'Luxor East & West Bank',
  'Full-day tour of Karnak, the Valley of the Kings, Hatshepsut Temple and the Colossi of Memnon (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '292598d3-84bb-44ef-91e2-ef22361ddc9f',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  7,
  'Return to Hurghada',
  'Transfer back to Hurghada, free beach evening (placeholder).'
);
INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '975238c6-160f-4ddf-9dbc-67a237acff29',
  '8fa42a74-7bd8-4649-94dd-7c7553ee480a',
  8,
  'Departure',
  'Check-out and airport transfer for your departure (placeholder).'
);

-- ===== Dahab (1 Day, €120) ====
INSERT INTO tours (id, title, slug, description, inclusions, exclusions, duration, base_price, currency, status, created_by, created_at) VALUES (
  'b61c4325-8073-4f52-81d7-1c699fa3ea82',
  'Dahab Tour',
  'dahab',
  'Escape to Dahab, the laid-back Bedouin town on the Gulf of Aqaba: the Blue Hole, the Canyon, Mount Sinai sunrise and golden beach time in the Red Sea.',
  'Private transfers
Snorkeling / diving trip (placeholder)
Lunch at a beach cafe
Bottled water',
  'Diving course fees
Mount Sinai trip (optional)
Tips and gratuities
Personal expenses',
  '1 Day',
  120,
  'EUR',
  'open',
  '56fd4067-1072-4a31-9830-7e73852d207d',
  NOW()
);

INSERT INTO tour_itineraries (id, tour_id, day_number, title, description) VALUES (
  '554e126d-5ada-4460-9dcc-40302b03c714',
  'b61c4325-8073-4f52-81d7-1c699fa3ea82',
  1,
  'Dahab, Blue Hole & Beach Time',
  'Discover the Blue Hole and the famous diving sites of Dahab, relax at the beach resorts and wander the Bedouin promenade (placeholder).'
);

COMMIT;

-- 16 tours, 46 itinerary entries